//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class amostrastb
    {
        public long id { get; set; }
        public long numordem { get; set; }
        public Nullable<System.DateTime> datarecepcao { get; set; }
        public string nit_nid { get; set; }
        public string NIT { get; set; }
        public string NID { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public Nullable<int> idade { get; set; }
        public string residencia { get; set; }
        public string telefone { get; set; }
        public string proveniencia { get; set; }
        public string tipoamostra { get; set; }
        public string causarejeicao { get; set; }
        public string tipodoente { get; set; }
        public string motivoexame { get; set; }
        public Nullable<int> mescontrolo { get; set; }
        public string usreferencia { get; set; }
        public Nullable<System.DateTime> dataenvio { get; set; }
        public string examesolicitado { get; set; }
        public string iniciaistecnicoenvio { get; set; }
        public string bkresultado1 { get; set; }
        public Nullable<System.DateTime> bkdatarecepcao1 { get; set; }
        public string bkresultado2 { get; set; }
        public Nullable<System.DateTime> bkdatarecepcao2 { get; set; }
        public string xpertresultado { get; set; }
        public Nullable<System.DateTime> xpertdatarecepcao { get; set; }
        public string rifresultado { get; set; }
        public Nullable<System.DateTime> rifdatarecepcao { get; set; }
        public string lpa1h_resultado { get; set; }
        public string lpa1r_resultado { get; set; }
        public Nullable<System.DateTime> lpa1datarecepcao { get; set; }
        public string lpa2fq_resultado { get; set; }
        public string lpa2ag_resultado { get; set; }
        public Nullable<System.DateTime> lpa2datarecepcao { get; set; }
        public string cultura { get; set; }
        public Nullable<System.DateTime> culturadatarecepcao { get; set; }
        public string idetinficacao { get; set; }
        public Nullable<System.DateTime> identificacaodata { get; set; }
        public string tsa1h_resultado { get; set; }
        public string tsa1s_resultado { get; set; }
        public string tsa1r_resultado { get; set; }
        public string tsa1e_resultado { get; set; }
        public string tsa1z_resultado { get; set; }
        public Nullable<System.DateTime> tsa1datarecepcao { get; set; }
        public string tsa2ofl_resultado { get; set; }
        public string tsa2mox_resultado { get; set; }
        public string tsa2kan_resultado { get; set; }
        public string tsa2amk_resultado { get; set; }
        public string tsa2cap_resultado { get; set; }
        public Nullable<System.DateTime> tsa2datarecepcao { get; set; }
        public Nullable<System.DateTime> dataenvioresultado { get; set; }
        public string iniciaistecnicodevolve { get; set; }
        public string obs { get; set; }
    }
}
