//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccrseg
    {
        public int id { get; set; }
        public int idchild { get; set; }
        public Nullable<bool> lostfollowup { get; set; }
        public Nullable<bool> death { get; set; }
        public Nullable<bool> ce2 { get; set; }
        public string defresult { get; set; }
        public Nullable<bool> ccs { get; set; }
        public Nullable<bool> ci { get; set; }
        public string ot_us { get; set; }
        public Nullable<bool> lostfollowup2 { get; set; }
        public Nullable<bool> death_2 { get; set; }
        public Nullable<bool> ce3 { get; set; }
        public string resultadofinal { get; set; }
        public string saidaccr { get; set; }
        public Nullable<bool> death_3 { get; set; }
    
        public virtual ccr ccr { get; set; }
    }
}
