//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccrseg
    {
        public int id { get; set; }
        public Nullable<int> idchild { get; set; }
        public int idccr { get; set; }
        public string mothTarv5moth { get; set; }
        public Nullable<bool> ame5m { get; set; }
        public Nullable<bool> am5m { get; set; }
        public Nullable<bool> recuperada { get; set; }
        public Nullable<bool> transinter { get; set; }
        public Nullable<bool> arv5m { get; set; }
        public Nullable<bool> pcrmen2m { get; set; }
        public Nullable<bool> pcrmai2m { get; set; }
        public Nullable<bool> pcrposmen2m { get; set; }
        public Nullable<bool> pcrposmai2m { get; set; }
        public Nullable<bool> tb { get; set; }
        public Nullable<bool> dam { get; set; }
        public Nullable<bool> dag { get; set; }
        public Nullable<bool> ce9m { get; set; }
        public Nullable<bool> pnctl { get; set; }
        public Nullable<bool> tpi { get; set; }
        public Nullable<bool> abandono9 { get; set; }
        public Nullable<bool> obito9 { get; set; }
        public Nullable<bool> ce18m { get; set; }
        public Nullable<bool> resultado18 { get; set; }
        public Nullable<bool> transferidaCCS { get; set; }
        public Nullable<bool> transferidaCI { get; set; }
        public Nullable<bool> transferidaUS { get; set; }
        public Nullable<bool> abandono18 { get; set; }
        public Nullable<bool> obito18 { get; set; }
    
        public virtual ccr ccr { get; set; }
    }
}
