//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public child()
        {
            this.ccrs = new HashSet<ccr>();
            this.ccrsegs = new HashSet<ccrseg>();
        }
    
        public int id { get; set; }
        public string nid_ccr { get; set; }
        public string name { get; set; }
        public string residence { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string mot_nid_cpn { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    
        public virtual ICollection<ccr> ccrs { get; set; }
        public virtual ICollection<ccrseg> ccrsegs { get; set; }
    }
}
