//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpn
    {
        public long id { get; set; }
        public Nullable<int> nr_consulta { get; set; }
        public long idmother { get; set; }
        public string nlivro { get; set; }
        public int nyear { get; set; }
        public System.DateTime visdate { get; set; }
        public string agegroup { get; set; }
        public Nullable<sbyte> gestationalage { get; set; }
        public Nullable<bool> gageless12 { get; set; }
        public Nullable<bool> partnerpresence { get; set; }
        public Nullable<int> weight { get; set; }
        public string weightgainyno { get; set; }
        public Nullable<bool> dag { get; set; }
        public Nullable<bool> dam { get; set; }
        public Nullable<int> supnutr { get; set; }
        public string resultcured { get; set; }
        public string resultabandon { get; set; }
        public string receiveddesparasitante { get; set; }
        public string salferr_acfolico { get; set; }
        public string ta { get; set; }
        public string hgb { get; set; }
        public string proteinuria { get; set; }
        public string glicosuria { get; set; }
        public Nullable<bool> its_ulceragenital { get; set; }
        public Nullable<bool> its_leucorreia { get; set; }
        public string its_syndromictreatment { get; set; }
        public string its_syphilistesting { get; set; }
        public string its_wsyphilistreat { get; set; }
        public string its_psyphilistreat { get; set; }
        public Nullable<bool> serostatusdesc { get; set; }
        public Nullable<bool> serostatusneg { get; set; }
        public Nullable<bool> serostatuspos { get; set; }
        public string cpnhivtest { get; set; }
        public string partnerhivtest { get; set; }
        public Nullable<bool> ctz { get; set; }
        public string ctz_init_cont { get; set; }
        public Nullable<bool> tarv { get; set; }
        public Nullable<bool> nvp { get; set; }
        public Nullable<bool> azt_nvp { get; set; }
        public Nullable<bool> tarv_init_visit { get; set; }
        public Nullable<bool> arv_cont { get; set; }
        public string tip { get; set; }
        public string bednet { get; set; }
        public string tdr_htz { get; set; }
        public string result_tdr_htz { get; set; }
        public string pos_malaria_treated { get; set; }
        public string hpp { get; set; }
        public Nullable<bool> vat_1_dose { get; set; }
        public Nullable<bool> vat_2_5_dose { get; set; }
        public string tb_isoniazid { get; set; }
        public string tb_treatment { get; set; }
        public string obs { get; set; }
        public string providername { get; set; }
    }
}
