//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpn_final
    {
        public long id { get; set; }
        public long idmother { get; set; }
        public string nlivro { get; set; }
        public Nullable<bool> cons_more4 { get; set; }
        public Nullable<bool> partnerpreence { get; set; }
        public string weightgainyno { get; set; }
        public Nullable<bool> dag { get; set; }
        public Nullable<bool> dam { get; set; }
        public string supnutr { get; set; }
        public string resultcured { get; set; }
        public string resultabandon { get; set; }
        public string receiveddesparasitante { get; set; }
        public Nullable<bool> salferr_more3 { get; set; }
        public Nullable<bool> its_diag { get; set; }
        public string its_treatment { get; set; }
        public string its_syphilistesting { get; set; }
        public Nullable<bool> its_wsyphilistreat { get; set; }
        public string its_psyphilistreat { get; set; }
        public string womanserostatus { get; set; }
        public string partnerserostatus { get; set; }
        public Nullable<bool> ctz_entr { get; set; }
        public Nullable<bool> ctz_init { get; set; }
        public string finalresult_arv { get; set; }
        public string tip { get; set; }
        public string bednet { get; set; }
        public string mal_diag_lab { get; set; }
        public string mal_treatment { get; set; }
        public string mp { get; set; }
        public Nullable<bool> vat_1_dose { get; set; }
        public Nullable<bool> vat_2_5_dose { get; set; }
        public Nullable<bool> tb_isoniazid { get; set; }
        public Nullable<bool> tb_treatment { get; set; }
    }
}
