//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpp
    {
        public long id { get; set; }
        public int nr_consulta { get; set; }
        public long idmother { get; set; }
        public string nlivro { get; set; }
        public System.DateTime visdate { get; set; }
        public Nullable<int> age { get; set; }
        public string localparto { get; set; }
        public string diasapoisparto { get; set; }
        public Nullable<int> parceiropresente { get; set; }
        public string estadorecemnascido { get; set; }
        public Nullable<bool> anemia { get; set; }
        public string e_clinicogenecologico { get; set; }
        public string outrapatologia { get; set; }
        public string dag_dam { get; set; }
        public string suplementonutricional { get; set; }
        public Nullable<bool> transferida { get; set; }
        public string almaternoexclusivo { get; set; }
        public string testemalaria { get; set; }
        public string resultado_TDR_HTZ { get; set; }
        public string puerperamalariatratada { get; set; }
        public string estadoentradacpp { get; set; }
        public string resultadocpp { get; set; }
        public string dosepuerpera { get; set; }
        public string iniciottosifiliscpp { get; set; }
        public string parceirottocpp { get; set; }
        public string seroestadoentradacpp { get; set; }
        public string testehivconsultacpp { get; set; }
        public Nullable<bool> emtarv { get; set; }
        public Nullable<bool> iniciatarv { get; set; }
        public Nullable<bool> continuatarv { get; set; }
        public Nullable<bool> rn_tarv { get; set; }
        public string testehivparceiro { get; set; }
        public string ttopuerpera { get; set; }
        public string rntto { get; set; }
        public string vitAcpp { get; set; }
        public string salferroso_acfolico { get; set; }
        public string transfistula { get; set; }
        public string rnccr { get; set; }
        public string transcsr_pf { get; set; }
        public string obs { get; set; }
        public string providername { get; set; }
    }
}
