//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratoriotb
    {
        public long id { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public string numlab { get; set; }
        public string nit_nid { get; set; }
        public string NIT { get; set; }
        public string NID { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public Nullable<int> idade { get; set; }
        public string residencia { get; set; }
        public string ocupacao { get; set; }
        public string telefone { get; set; }
        public string usreferencia { get; set; }
        public string proveniencia { get; set; }
        public string HIV { get; set; }
        public string ot_imunodepressao { get; set; }
        public string tipodoente { get; set; }
        public string motivoexame { get; set; }
        public Nullable<int> mescontrolo { get; set; }
        public string examesolicitado { get; set; }
        public Nullable<System.DateTime> datacolheita1 { get; set; }
        public Nullable<System.DateTime> datacolheita2 { get; set; }
        public Nullable<System.DateTime> datarecepcao1 { get; set; }
        public Nullable<System.DateTime> datarecepcao2 { get; set; }
        public string tipoamostra { get; set; }
        public string aspectomicro1 { get; set; }
        public string aspectomicro2 { get; set; }
        public string resultadobk1 { get; set; }
        public Nullable<System.DateTime> dataresultadobk1 { get; set; }
        public string resultadobk2 { get; set; }
        public Nullable<System.DateTime> dataresultadobk2 { get; set; }
        public string resultadomtb { get; set; }
        public Nullable<System.DateTime> dataresultadomtb { get; set; }
        public string resultadorif { get; set; }
        public Nullable<System.DateTime> dataresultadorif { get; set; }
        public string repetirxpert { get; set; }
        public string iniciaistecinico { get; set; }
        public string obs { get; set; }
    }
}
