//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro
    {
        public string nlivro { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public string uscode { get; set; }
        public string usname { get; set; }
        public System.DateTime initdate { get; set; }
        public string tipolivro { get; set; }
        public int ID { get; set; }
    }
}
