//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mother
    {
        public int id { get; set; }
        public string nid_cpn { get; set; }
        public string nid_tarv { get; set; }
        public string name { get; set; }
        public string residence { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    }
}
