//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientetb
    {
        public long id { get; set; }
        public int ano { get; set; }
        public System.DateTime dataregisto { get; set; }
        public string NIT { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public bool grupoetario { get; set; }
        public string residencia { get; set; }
        public string telefone { get; set; }
        public string ocupacao { get; set; }
        public string proveniencia { get; set; }
        public string localizacaolesao { get; set; }
        public string categoriadoente { get; set; }
        public System.DateTime datainiciotto { get; set; }
        public string casonovoadulto { get; set; }
        public string casonovocrianca { get; set; }
        public string retratamento { get; set; }
        public Nullable<bool> tbresistente { get; set; }
        public string nit_tbresistente { get; set; }
        public string fintensivalocal { get; set; }
        public string fintensivanomelocal { get; set; }
        public string fmanutencaolocal { get; set; }
        public string fmanutencaonomelocal { get; set; }
        public string testado { get; set; }
        public string hivresultado { get; set; }
        public string tpc { get; set; }
        public string emtarv { get; set; }
        public string NID { get; set; }
        public Nullable<System.DateTime> datainiciotarv { get; set; }
        public Nullable<int> contactosrastreados { get; set; }
        public Nullable<int> contactoscomtb { get; set; }
        public Nullable<int> criancasrastreadas { get; set; }
        public Nullable<int> criancasquimioproflaxia { get; set; }
        public Nullable<System.DateTime> bkdata { get; set; }
        public string bkresultado { get; set; }
        public string bknumlab { get; set; }
        public Nullable<System.DateTime> gxrifdata { get; set; }
        public string gxresultado { get; set; }
        public string rifresultado { get; set; }
        public string gxrifnumlab { get; set; }
        public Nullable<System.DateTime> culturadata { get; set; }
        public string culturaresultado { get; set; }
        public string culturanumlab { get; set; }
        public string rx { get; set; }
        public string outrosexames { get; set; }
        public Nullable<System.DateTime> bact_bkdata_2_3 { get; set; }
        public string bact_bkresultado_2_3 { get; set; }
        public string bact_bknumlab_2_3 { get; set; }
        public Nullable<System.DateTime> bact_culturadata_2_3 { get; set; }
        public string bact_culturaresultado_2_3 { get; set; }
        public string bact_culturanumlab_2_3 { get; set; }
        public Nullable<System.DateTime> bact_bkdata_5 { get; set; }
        public string bact_bkresultado_5 { get; set; }
        public string bact_bknumlab_5 { get; set; }
        public Nullable<System.DateTime> bact_culturadata_5 { get; set; }
        public string bact_culturaresultado_5 { get; set; }
        public string bact_culturanumlab_5 { get; set; }
        public Nullable<System.DateTime> bact_bkdata_fimtrat { get; set; }
        public string bact_bkresultado_fimtrat { get; set; }
        public string bact_bknumlab_fimtrat { get; set; }
        public Nullable<System.DateTime> bact_culturadata_fimtrat { get; set; }
        public string bact_culturaresultado_fimtrat { get; set; }
        public string bact_culturanumlab_fimtrat { get; set; }
        public Nullable<System.DateTime> datafimtratamento { get; set; }
        public string resultadotratamento { get; set; }
        public Nullable<int> tb_resistente { get; set; }
        public string obs { get; set; }
    }
}
