//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente_resistente_tb
    {
        public long id { get; set; }
        public string distrito { get; set; }
        public string us { get; set; }
        public Nullable<System.DateTime> dataregisto { get; set; }
        public string NIT2 { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public Nullable<bool> grupoetario { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string ocupacao { get; set; }
        public string NIT { get; set; }
        public Nullable<System.DateTime> dataregistotb { get; set; }
        public string localizacaolesao { get; set; }
        public string categoriadoete { get; set; }
        public string ttoprevio2l { get; set; }
        public Nullable<bool> diagconfirmadopor { get; set; }
        public Nullable<System.DateTime> datacolheitatsa { get; set; }
        public Nullable<System.DateTime> dataresultadotsa { get; set; }
        public Nullable<bool> sensibilidade_s { get; set; }
        public Nullable<bool> sensibilidade_h { get; set; }
        public Nullable<bool> sensibilidade_r { get; set; }
        public Nullable<bool> sensibilidade_e { get; set; }
        public Nullable<bool> sensibilidade_z { get; set; }
        public Nullable<bool> sensibilidade_Amk_Km { get; set; }
        public Nullable<bool> sensibilidade_cm { get; set; }
        public Nullable<bool> sensibilidade_FQ { get; set; }
        public Nullable<bool> sensibilidade_Pto_Eto { get; set; }
        public string sensibilidade_Outro1 { get; set; }
        public string sensibilidade_Outro2 { get; set; }
        public string sensibilidade_Outro3 { get; set; }
        public string perfilresistencia { get; set; }
        public Nullable<int> contactosrastreadostbr { get; set; }
        public Nullable<int> contactoscomtbr { get; set; }
        public string tastehiv { get; set; }
        public Nullable<System.DateTime> dataresultadohiv { get; set; }
        public string tpc { get; set; }
        public Nullable<System.DateTime> datainiciotpc { get; set; }
        public string emtarv { get; set; }
        public string NID { get; set; }
        public Nullable<System.DateTime> datainiciotarv { get; set; }
        public string regimetratamento { get; set; }
        public string ustratamento { get; set; }
        public Nullable<System.DateTime> usdatainiciotto { get; set; }
        public string comtratamento { get; set; }
        public Nullable<System.DateTime> comdatainiciotto { get; set; }
        public string resultadobk_0m { get; set; }
        public Nullable<System.DateTime> dataresultadobk_0m { get; set; }
        public string resultadocultura_0m { get; set; }
        public Nullable<System.DateTime> dataresultadocultura_0m { get; set; }
        public string resultadobk_1m { get; set; }
        public string resultadocultura_1m { get; set; }
        public Nullable<System.DateTime> dataresultado_1m { get; set; }
        public string resultadobk_2m { get; set; }
        public string resultadocultura_2m { get; set; }
        public Nullable<System.DateTime> dataresultado_2m { get; set; }
        public string resultadobk_3m { get; set; }
        public string resultadocultura_3m { get; set; }
        public Nullable<System.DateTime> dataresultado_3m { get; set; }
        public string resultadobk_4m { get; set; }
        public string resultadocultura_4m { get; set; }
        public Nullable<System.DateTime> dataresultado_4m { get; set; }
        public string resultadobk_5m { get; set; }
        public string resultadocultura_5m { get; set; }
        public Nullable<System.DateTime> dataresultado_5m { get; set; }
        public string resultadobk_6m { get; set; }
        public string resultadocultura_6m { get; set; }
        public Nullable<System.DateTime> dataresultado_6m { get; set; }
        public string estadopaciente6meses { get; set; }
        public string resultadobk_7m { get; set; }
        public string resultadocultura_7m { get; set; }
        public Nullable<System.DateTime> dataresultado_7m { get; set; }
        public string resultadobk_8m { get; set; }
        public string resultadocultura_8m { get; set; }
        public Nullable<System.DateTime> dataresultado_8m { get; set; }
        public string resultadobk_9m { get; set; }
        public string resultadocultura_9m { get; set; }
        public Nullable<System.DateTime> dataresultado_9m { get; set; }
        public string resultadobk_10m { get; set; }
        public string resultadocultura_10m { get; set; }
        public Nullable<System.DateTime> dataresultado_10m { get; set; }
        public string resultadobk_11m { get; set; }
        public string resultadocultura_11m { get; set; }
        public Nullable<System.DateTime> dataresultado_11m { get; set; }
        public string resultadobk_12m { get; set; }
        public string resultadocultura_12m { get; set; }
        public Nullable<System.DateTime> dataresultado_12m { get; set; }
        public string estadopaciente12meses { get; set; }
        public string resultadobk_14m { get; set; }
        public string resultadocultura_14m { get; set; }
        public Nullable<System.DateTime> dataresultado_14m { get; set; }
        public string resultadobk_16m { get; set; }
        public string resultadocultura_16m { get; set; }
        public Nullable<System.DateTime> dataresultado_16m { get; set; }
        public string resultadobk_18m { get; set; }
        public string resultadocultura_18m { get; set; }
        public Nullable<System.DateTime> dataresultado_18m { get; set; }
        public string estadopaciente18meses { get; set; }
        public string resultadobk_20m { get; set; }
        public string resultadocultura_20m { get; set; }
        public Nullable<System.DateTime> dataresultado_20m { get; set; }
        public string resultadobk_22m { get; set; }
        public string resultadocultura_22m { get; set; }
        public Nullable<System.DateTime> dataresultado_22m { get; set; }
        public string resultadobk_24m { get; set; }
        public string resultadocultura_24m { get; set; }
        public Nullable<System.DateTime> dataresultado_24m { get; set; }
        public string estadopaciente24meses { get; set; }
        public string resultadobk_26m { get; set; }
        public string resultadocultura_26m { get; set; }
        public Nullable<System.DateTime> dataresultado_26m { get; set; }
        public string resultadobk_28m { get; set; }
        public string resultadocultura_28m { get; set; }
        public Nullable<System.DateTime> dataresultado_28m { get; set; }
        public string resultadobk_30m { get; set; }
        public string resultadocultura_30m { get; set; }
        public Nullable<System.DateTime> dataresultado_30m { get; set; }
        public string estadopaciente30meses { get; set; }
        public string resultadofinaltto { get; set; }
        public Nullable<System.DateTime> datafimtto { get; set; }
        public string obs { get; set; }
        public string nometecnico { get; set; }
    }
}
