//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string apelido { get; set; }
        public string password { get; set; }
        public string posicao { get; set; }
        public string systemrole { get; set; }
    }
}
